Algoritmo "Contar e somar"
Var
   valor, numero, soma : inteiro
Inicio
      numero <- 1
      soma <- 0
      escreva("Quantos números deseja contar? ")
      leia(valor)
       enquanto ( numero <= valor ) faca
        escreval("contador: ",numero)
        soma <- soma + numero
        numero <- numero + 1
        fimenquanto
        escreval("A soma de todos os valores foi de: ",soma)
      escreval("Terminei de contar")
      
Fimalgoritmo
