Algoritmo "Cotação dolar"
Var
   reais1:real
   dolar1, dolar2:real
Inicio
      escreva("Quantos reais você tem? ")
      leia(reais1)
      dolar1 <-  5.48
      dolar2 <- 2.34
      escreval("Atualmente com a cotação do dolar de ", dolar1 )
      escreval(" Você possui ", reais1/dolar1, " Dolares")
      escreval("Em 2022 você teria ", reais1/dolar1 , " dolares. Em 2014 ", reais1/dolar2 )
Fimalgoritmo